model_name = "google-bert/bert-large-uncased"
matryoshka_dims = [768, 512, 256, 128, 64]
batch_size = 32
num_train_epochs = 15
output_dir = "./outputs/train/bert-large-uncased/mrl-768-512-256-128-64/"
